### ISSUE TITLE
Why mindful sessions are not supported?

### ISSUE THREAD

**Issue by leolorenzoluis** [twstokes/healthdata_influx#4]

**Comment by twstokes** [comment]
No particular reason other than I didn't need them for my original implementation. PRs are welcome!

**Comment by leolorenzoluis** [comment]
Ah I thought you also encountered what I encountered. Mindful sessions and sleep data are not exporting from Apple health for me. I don't know why.

**Comment by twstokes** [comment]
I want to think I was able to see mindful sessions, but just didn't feel like parsing them.

**Comment by leolorenzoluis** [comment]
Ah, I haven't actually tried running docker but does the refresh data will actually repopulate the data in influxdb with only the records that are added or there will be duplicates?

**Comment by twstokes** [comment]
I believe InfluxDB will do a union of the duplicate points (and in this case, nothing should change), so it'll essentially ignore duplicates. It's really inefficient to start from the beginning each time, though, so this code could be improved by keeping track of the last imported record.

**Comment by leolorenzoluis** [comment]
@twstokes I'm new to Grafana. Do you have a step by step on how to query InfluxDB with the field names? I'm sure I can figure it out with accessing the scripts and looking at the field names but for new users I think it'll be helpful

**Comment by twstokes** [comment]
@leolorenzoluis If you fire the project up in Docker it may be helpful to see where Grafana is querying the data. The graphs are configured on startup.
