### ISSUE TITLE
Unable to find image / docker login

### ISSUE THREAD

**Issue by mschindl** [twstokes/healthdata_influx#6]
I'm logged in docker, but I got following message:

_Unable to find image 'twstokes/healthdata_influx:latest' locally
docker: Error response from daemon: pull access denied for twstokes/healthdata_influx, repository does not exist or may require 'docker login'_

I tried following run command:

docker run \
-d \
-p 3000:3000 \
-e UID=1000 \
-e GID=1000 \
-e TZ='Europe/Berlin' \
-v /DATAINT/Docker-Conf/healthdata/data:/data:ro \
-v /DATAINT/Docker-Conf/healthdata/config.yml:/app/config.yml:ro \
--name healthdata \
twstokes/healthdata_influx:latest

root@Server:~# ll /DATAINT/Docker-Conf/healthdata/data
total 1
drwxrwx--- 2 user user 2 Jun 22 23:12 ./
drwxrwx--- 3 user user 3 Jun 22 23:12 ../

Any idea?

**Comment by twstokes** [comment]
Hi @mschindl - did you complete the build step first with `docker build . -t twstokes/healthdata_influx`? This image isn't uploaded anywhere so you have to build it locally first.
