### ISSUE TITLE
Not able to visualize SleepData

### ISSUE THREAD

**Issue by AlfaJackal** [twstokes/healthdata_influx#7]
How do I visualize my sleep data? As you can see, data is available, but if I try to make a graph, it shows nothing.

My guess is that is has something to do with the fact that these sleeping data is formatted as log and not metrics. 

![image](https://user-images.githubusercontent.com/17096950/85129460-71c47c80-b233-11ea-85f6-3d41917557b9.jpeg)

![image](https://user-images.githubusercontent.com/17096950/85129560-96205900-b233-11ea-9821-f75450772cd5.jpeg)

Would love to show those aswell!

**Comment by twstokes** [comment]
Unfortunately I don't have anything to generate "is asleep" data, but I do have some records for "is in bed". Apple has three types for this record documented here: https://developer.apple.com/documentation/healthkit/hkcategoryvaluesleepanalysis

I think this is more of an Influx / Grafana issue you're running into where you need to determine how to stitch together data points to make it continuous over time.
