### ISSUE TITLE
Is there a license for this repo?

### ISSUE THREAD

**Issue by saintaardvark** [twstokes/healthdata_influx#8]
Hi there -- I came across this repo, and I really like it -- I had been thinking I'd have to write something myself to parse the health data, and I'm glad to see someone has beat me to the punch. :grin: 

Is there a license for this repo? I would really like to be able to be able to use this as a base for other things, but I don't want to step on any toes.

Thanks again for publishing this!

**Comment by twstokes** [comment]
Hey @saintaardvark 👋 , thanks for asking! I've just committed 2dab351eef7f114c2555f1a09f8851f3da32f300 which includes the MIT license.

**Comment by saintaardvark** [comment]
That's awesome -- thank you so much for sharing!
